### ISSUE TITLE
how can we get the scroll percentage 

### ISSUE THREAD

**Issue by ahsansuhail** [nihad92/SwipeableCards#16]
Hi, how can we get the scroll percentage or is there any OnScroll listener in the library?

**Comment by nihad92** [comment]
Hi, 
Yes, library support swipe percentage. If you want to follow swipe percentage of a specific card, `ViewHolder` of the card have to implement `OnItemSwipePercentageListener` and that's it. 
For example:
`FeedCardVH extends FeedCardBaseVH implements OnItemSwipePercentageListener {
  @Override public void onItemSwipePercentage(double v) {
     //v is in range  0..1
  }
}`

**Comment by ahsansuhail** [comment]
But i want to get the scroll percentage wherever i drag the card. not just limited to left and right.

**Comment by ahsansuhail** [comment]
Got it.
