### ISSUE TITLE
How to disable swipe temporarity?

### ISSUE THREAD

**Issue by Dewsworld** [nihad92/SwipeableCards#21]
Hello! 
This has been a good library so far. In my situation, I need to temporarily disable swiping (eg. `disableSwipe()` and then` enableSwipe()` ). When I disable swipe, swiping animation should render but the swiped card should return back to where it was at the top place. Is there any way I can achieve this? 

Thanks!

**Comment by nihad92** [comment]
Hello 
Yes there is, and it is possible to do for specific ViewHolder or for all of them, so you can use override method in SwipeableTouchHelperCallback 
`public int getAllowedSwipeDirectionsMovementFlags(RecyclerView.ViewHolder viewHolder) {
if(disable) {
    return 0;
} else {
   return ItemTouchHelper.LEFT | ItemTouchHelper.RIGHT
}
  }`
or with specific case for specific viewholder
