### ISSUE TITLE
Add onItemSwipedUp and Down

### ISSUE THREAD

**Issue by webserveis** [nihad92/SwipeableCards#4]
Tinder has a Super like when swipe to up.

It would be interesting to allow up and down with a property to block the side we want

**Comment by nihad92** [comment]
Hi, it took some time but finally with Release 1.0.12, we are supporting swipe up and down. Also, there is an additional method in `SwipeableTouchHelperCallback` class for blocking swipe to a specific side
`public int getAllowedSwipeDirectionsMovementFlags(RecyclerView.ViewHolder viewHolder)`

So if you want to block swiping down you should override `getAllowedSwipeDirectionsMovementFlags(RecyclerView.ViewHolder viewHolder) {
    return ItemTouchHelper.UP | ItemTouchHelper.RIGHT | ItemTouchHelper.LEFT;
}`
