### ISSUE TITLE
How to restrict Upwards and downwards swiping. 

### ISSUE THREAD

**Issue by ashokslsk** [nihad92/SwipeableCards#5]
Hey there, 

The effort you have put in for this library is prominent. But your documentation needs a little work and also how do I restrict users to not to move around the card and just only swipe left and right. and show the deck of cards.

**Comment by nihad92** [comment]
Hi, @ashokslsk Thanks for reporting the issue. I am going to add support for restricting movement to the specific direction and restriction of swiping to the specific direction. 
So you will be available to provide directions by overriding **getAllowedDirectionsMovementFlags** method in **SwipeableTouchHelperCallback** class. So if you want to disable moving card up and down  methode should look like this 

`
new SwipeableTouchHelperCallback() {
@Override  public int getAllowedDirectionsMovementFlags() {
    return ItemTouchHelper.LEFT | ItemTouchHelper.RIGHT;
  }
}`

Also showing deck  is possible by setting **setTransYGap(value in pixels).setScaleGap(0)**
