### ISSUE TITLE
How to programatically swipe left or right?

### ISSUE THREAD

**Issue by YuriAR** [nihad92/SwipeableCards#6]
I need a way to press a button and swipe left/right. Is there a way to do this?

**Comment by nihad92** [comment]
Thanks for reporting the issue currently library does not support programmatically swiping cards. 
I will add support in next few days method signature should look like this: **void swipe(int direction)**
where the direction is one of following values ItemTouchHelper.LEFT, ItemTouchHelper.RIGHT, ItemTouchHelper.UP, ItemTouchHelper.DOWN

**Comment by anshusharma13** [comment]
hello @nihad92  could you please give the solution for swiping the card by button .

**Comment by ashokslsk** [comment]
@nihad92 were you able to update this feature in the current library. ?

**Comment by anshusharma13** [comment]
Its very helpful, i tried so many libraries but the scroll in the item not working but in this every thing is perfect fine except button swipe

**Comment by anshusharma13** [comment]
if anybody know the scroll  inside the item in  tinder swipe view  then please let me know

**Comment by nihad92** [comment]
Hi guys, 
Finally, I managed to add support for swiping cards programmatically. 
Swipe on click is available in Release 1.0.19. The method is available in ItemTouchHelper
`        itemTouchHelper.swipe(recyclerView.findViewHolderForAdapterPosition(0), ItemTouchHelper.DOWN);
`
