### ISSUE TITLE
Undo functionality

### ISSUE THREAD

**Issue by enriquejuan2** [nihad92/SwipeableCards#7]
Is there any way to implement undo functionality in this library?

**Comment by nihad92** [comment]
Hi, If you want undo functionality with reverse animation no there is no way to do that. But if you want simply add back item yes, same as with every other recycler view.
After removing item in onItemSwiped method you will have to preserve removed item model from adapter and on undo button clicked you will simply add item to position 0 and call notifyItemInserted.
